version: '3'


services:

  nginx:
    image: bogardo/nginx:1.0
    ports:
     - "80:80"
    volumes:
     - ./application:/var/www/html
     - ./docker/logs/nginx:/var/log/nginx
    working_dir: /var/www/html
    networks:
     - appnet

  php:
    image: bogardo/php70:1.0
    volumes:
     - ./application:/var/www/html
    working_dir: /var/www/html
    networks:
     - appnet

  node:
    image: bogardo/node:1.0
    volumes:
     - ./application:/var/www/html
    working_dir: /var/www/html
    command: tail -f /dev/null
    networks:
     - appnet

  redis:
    image: redis:alpine
    volumes:
     - ./docker/logs/redis:/var/log/redis
    networks:
     - appnet

  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: homestead
      MYSQL_USER: homestead
      MYSQL_PASSWORD: secret
    ports:
     - "3306:3306"
    volumes:
     - data:/var/lib/mysql
     - ./docker/logs/mysql:/var/log/mysql
    networks:
     - appnet

networks:
  appnet:
    driver: "bridge"


volumes:
  data:
    driver: "local"